name: "Family Chore Tracker"
description: "A comprehensive family chore management system with points, rewards, and statistics"
version: "1.1.3"
slug: "family-chore-tracker"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
map:
  - "config:rw"
  - "ssl"
ports:
  "9123/tcp": 9123
webui: "http://[HOST]:[PORT:9123]"
ingress: true
ingress_port: 9123
panel_icon: "mdi:clipboard-check"
panel_title: "Chore Tracker"
hassio_api: true
hassio_role: default
options:
  database_path: "/data/chores.db"
  port: 9123
  log_level: "info"
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  database_path: "str"
  port: "port"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  ssl: "bool"
  certfile: "str"
  keyfile: "str"
# image: "ghcr.io/tadejbartol/ha-family-chore-tracker-{arch}"
# Build locally - no GitHub registry needed 
